version: '3'

services:
  web:
    image: 651706736417.dkr.ecr.us-east-1.amazonaws.com/japan-prayer-guide:latest
    ports:
      - "32529:3000"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - NODE_ENV=production
    restart: always
